version: "3.8"
services:
  db:
    image: postgres:15
    container_name: booking_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
  booking:
    build:
      context: .
    volumes:
      - .:/booking
    container_name: booking_app
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "chmod a+x docker/*.sh && docker/app.sh"
    ports:
      - 7777:8000
volumes:
  postgresdata:
