"""empty message

Revision ID: d301512bcdca
Revises: c02279eea27e
Create Date: 2023-10-17 20:43:24.500609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd301512bcdca'
down_revision: Union[str, None] = 'c02279eea27e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('services', sa.JSON(), nullable=True))
    op.drop_column('hotels', 'service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('service', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('hotels', 'services')
    # ### end Alembic commands ###
